# Generated by Django 4.0.4 on 2022-05-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='v1653639639/profiles/developer_ul4jhe.jpg', null=True, upload_to='profiles/'),
        ),
    ]
